name: Register

on:
  schedule:
    - cron: "0 0 */6 * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Run Register Script
        run: bash register.sh
